//! Conformance with the reference vectors generated by the TypeScript engine (spec §5.1).

use crash_rules::*;
use serde_json::Value;

const VECTORS: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../../docs/specs/vectors/crash-rules-v1.json"
));

fn vectors() -> Value {
    serde_json::from_str(VECTORS).expect("valid vectors JSON")
}

fn num(value: &Value) -> u64 {
    value
        .as_str()
        .expect("bigint encoded as string")
        .parse()
        .expect("u64")
}

fn opt_num(value: &Value) -> Option<u64> {
    if value.is_null() {
        None
    } else {
        Some(num(value))
    }
}

fn entropy(hex: &str) -> [u8; ENTROPY_BYTES] {
    let mut bytes = [0u8; ENTROPY_BYTES];
    for (index, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[index * 2..index * 2 + 2], 16).expect("hex");
    }
    bytes
}

#[test]
fn rules_match_v1() {
    let v = vectors();
    assert_eq!(
        v["rulesVersion"].as_u64(),
        Some(CRASH_RULES_V1.version as u64)
    );
    assert_eq!(
        num(&v["rules"]["houseEdgeBps"]),
        CRASH_RULES_V1.house_edge_bps
    );
    assert_eq!(num(&v["rules"]["growthPpm"]), CRASH_RULES_V1.growth_ppm);
    assert_eq!(
        num(&v["rules"]["maxMultiplier"]),
        CRASH_RULES_V1.max_multiplier
    );
}

#[test]
fn curve_matches() {
    let v = vectors();
    let curve = v["curve"].as_array().unwrap();
    assert_eq!(CRASH_RULES_V1.horizon().unwrap(), curve.len() as u64);
    for (tick, point) in curve.iter().enumerate() {
        assert_eq!(
            CRASH_RULES_V1.multiplier_at_tick(tick as u64).unwrap(),
            num(point),
            "tick {tick}"
        );
    }
    assert_eq!(
        CRASH_RULES_V1.multiplier_at_tick(curve.len() as u64),
        Err(RulesError::TickOutsideHorizon)
    );
}

#[test]
fn crash_points_match() {
    let v = vectors();
    for case in v["crashPoints"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let bytes = entropy(case["entropy"].as_str().unwrap());
        assert_eq!(
            uniform_from_entropy(&bytes),
            num(&case["uniform"]),
            "{name}"
        );
        assert_eq!(
            CRASH_RULES_V1.crash_point_from_entropy(&bytes).unwrap(),
            num(&case["crashPoint"]),
            "{name}"
        );
    }
}

/// The on-chain program records only a bet's first *accepted* cash-out: requests below 1.01x or
/// beyond the horizon are rejected at submission, and the earliest accepted one has the lowest tick.
fn recorded_cash_out_tick(cash_outs: &[Value], bet_id: &str, horizon: u64) -> Option<u64> {
    cash_outs
        .iter()
        .filter(|request| request["betId"] == bet_id)
        .filter_map(|request| request["tick"].as_u64())
        .filter(|&tick| {
            tick < horizon
                && CRASH_RULES_V1.recognized_at_tick(tick).unwrap() >= MIN_CASH_OUT_MULTIPLIER
        })
        .min()
}

#[test]
fn settlements_match() {
    let v = vectors();
    let horizon = CRASH_RULES_V1.horizon().unwrap();
    for case in v["settlements"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let kind = case["kind"].as_str().unwrap();
        let cash_outs = case["cashOuts"].as_array().unwrap();
        if kind == "reveal" {
            assert_eq!(
                CRASH_RULES_V1.crash_tick(num(&case["crashPoint"])).unwrap(),
                case["crashTick"].as_u64().unwrap(),
                "{name}"
            );
        }

        let mut total_payout = 0u64;
        let bets = case["bets"].as_array().unwrap();
        let expected = case["expected"]["settlements"].as_array().unwrap();
        assert_eq!(bets.len(), expected.len(), "{name}");
        for (bet, expected) in bets.iter().zip(expected) {
            let bet_id = bet["id"].as_str().unwrap();
            let stake = num(&bet["stake"]);
            let auto = opt_num(&bet["autoCashOut"]);
            let tick = recorded_cash_out_tick(cash_outs, bet_id, horizon);
            let outcome = match kind {
                "reveal" => {
                    settle_bet(&CRASH_RULES_V1, stake, auto, tick, num(&case["crashPoint"]))
                        .unwrap()
                }
                "forfeit" => settle_forfeited_bet(&CRASH_RULES_V1, stake, auto, tick).unwrap(),
                "refund" => refund_bet(stake),
                other => panic!("unknown kind {other}"),
            };
            let expected_outcome = match expected["outcome"].as_str().unwrap() {
                "cashed-out" => Outcome::CashedOut {
                    multiplier: num(&expected["multiplier"]),
                    payout: num(&expected["payout"]),
                },
                "lost" => Outcome::Lost,
                "refunded" => Outcome::Refunded {
                    payout: num(&expected["payout"]),
                },
                other => panic!("unknown outcome {other}"),
            };
            assert_eq!(outcome, expected_outcome, "{name} / {bet_id}");
            total_payout += outcome.payout();
        }
        assert_eq!(
            total_payout,
            num(&case["expected"]["totalPayout"]),
            "{name}"
        );
    }
}

#[test]
fn bet_validation_matches() {
    let v = vectors();
    let section = &v["betValidation"];
    let limits = BetLimits {
        min_stake: num(&section["limits"]["minStake"]),
        max_stake: num(&section["limits"]["maxStake"]),
        max_payout: num(&section["limits"]["maxPayout"]),
        max_round_exposure: num(&section["limits"]["maxRoundExposure"]),
    };
    let max_multiplier = num(&section["maxMultiplier"]);
    for case in section["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let result = validate_bet(
            num(&case["bet"]["stake"]),
            opt_num(&case["bet"]["autoCashOut"]),
            &limits,
            max_multiplier,
        );
        let expected = &case["expected"];
        if expected["ok"].as_bool().unwrap() {
            assert_eq!(result, Ok(num(&expected["value"])), "{name}");
        } else {
            let reason = match expected["error"].as_str().unwrap() {
                "stake-below-minimum" => BetRejection::StakeBelowMinimum,
                "stake-above-maximum" => BetRejection::StakeAboveMaximum,
                "auto-cash-out-not-centi-precise" => BetRejection::AutoCashOutNotCentiPrecise,
                "auto-cash-out-below-minimum" => BetRejection::AutoCashOutBelowMinimum,
                "auto-cash-out-above-maximum" => BetRejection::AutoCashOutAboveMaximum,
                "payout-above-maximum" => BetRejection::PayoutAboveMaximum,
                other => panic!("unknown rejection {other}"),
            };
            assert_eq!(result, Err(reason), "{name}");
        }
    }
}
