import { PublicKey } from "@solana/web3.js";
import type { IdlField, IdlType, IdlTypeDef, TypeRegistry } from "./borsh";
import idlJson from "./idl/crash.json";

/**
 * The IDL generated by `anchor build` for the deployed program is the codec's source of truth
 * (docs/specs/crash-client-v1.md §3). Regenerate `idl/crash.json` only when the program changes.
 */

export interface IdlInstructionAccount {
  name: string;
  writable?: boolean;
  signer?: boolean;
  optional?: boolean;
  address?: string;
}

export interface IdlInstruction {
  name: string;
  discriminator: number[];
  accounts: IdlInstructionAccount[];
  args: IdlField[];
}

export interface IdlNamedDiscriminator {
  name: string;
  discriminator: number[];
}

export interface CrashIdl {
  address: string;
  instructions: IdlInstruction[];
  accounts: IdlNamedDiscriminator[];
  events: IdlNamedDiscriminator[];
  errors: { code: number; name: string; msg?: string }[];
  types: IdlTypeDef[];
}

export const CRASH_IDL = idlJson as unknown as CrashIdl;

export const CRASH_IDL_TYPES: TypeRegistry = new Map(CRASH_IDL.types.map((def) => [def.name, def]));

export const CRASH_IDL_PROGRAM_ID = new PublicKey(CRASH_IDL.address);

export function idlInstruction(name: string): IdlInstruction {
  const instruction = CRASH_IDL.instructions.find((candidate) => candidate.name === name);
  if (!instruction) throw new Error(`IDL: unknown instruction ${name}`);
  return instruction;
}

export function idlAccountDiscriminator(name: string): Uint8Array {
  const account = CRASH_IDL.accounts.find((candidate) => candidate.name === name);
  if (!account) throw new Error(`IDL: unknown account ${name}`);
  return Uint8Array.from(account.discriminator);
}

export function idlTypeDef(name: string): IdlTypeDef {
  const def = CRASH_IDL_TYPES.get(name);
  if (!def) throw new Error(`IDL: unknown type ${name}`);
  return def;
}

export function definedType(name: string): IdlType {
  return { defined: { name } };
}
